=== Robb-Fr/nginx.org/dtd/i18n.dtd
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!ELEMENT  i18n         (text+) >

<!ELEMENT  text         (item+) >
<!ATTLIST  text
           lang         CDATA #REQUIRED
>

<!ELEMENT  item         (#PCDATA) >
<!ATTLIST  item
           id           CDATA #REQUIRED
>

=== Robb-Fr/nginx.org/xml/i18n.xml
<!DOCTYPE i18n SYSTEM "../dtd/i18n.dtd">

<i18n>

<text lang="en">
<item id="and">and</item>
<item id="author">written by</item>
<item id="editor">edited by</item>
<item id="translator">translated by</item>
<item id="syntax">syntax</item>
<item id="default">default</item>
<item id="context">context</item>
<item id="context.any">any</item>
<item id="directive.version">This directive appeared in version</item>
<item id="directive.versions">This directive appeared in versions</item>
</text>

<text lang="ru">
<item id="and">и</item>
<item id="syntax">синтаксис</item>
<item id="default">умолчание</item>
<item id="context">контекст</item>
<item id="context.any">любой</item>
<item id="directive.version">Эта директива появилась в версии</item>
<item id="directive.versions">Эта директива появилась в версиях</item>
</text>

<text lang="ja">
<item id="author">作成:</item>
<item id="translator">翻訳:</item>
</text>

<text lang="he">
<item id="author">נכתב על ידי</item>
<item id="translator">תורגם על ידי</item>
</text>

<text lang="tr">
<item id="author">yazan:</item>
<item id="translator">çeviren:</item>
</text>

</i18n>
